import sys
import pygame

def check_events():
    """Reactions for the events generated by mouse and keyboard"""
    # Waiting for push any button
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()

def update_screen(ai_settings, screen, ship):
    """Update images show on screen"""
    screen.fill(ai_settings.bg_color)
    ship.blitme()

    # Show last modified screen
    pygame.display.flip()