import sys
import pygame

def check_events(ship):
    """Reactions for the events generated by mouse and keyboard"""
    # Waiting for push any button
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()

        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_RIGHT:
                ship.moving_right = True
            elif event.key == pygame.K_LEFT:
                ship.moving_left = True

        elif event.type == pygame.KEYUP:
            if event.key == pygame.K_RIGHT:
                ship.moving_right = False
            elif event.key == pygame.K_LEFT:
                ship.moving_left = False


def update_screen(ai_settings, screen, ship):
    """Update images show on screen"""
    screen.fill(ai_settings.bg_color)
    ship.blitme()

    # Show last modified screen
    pygame.display.flip()